# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f4f81a884a588b5e03540a8c178c9692abe3dbae372ba6f01eeff7323b9cdf7ccbf9b0df739a08ea3b6faef12f3102289a52fb549a1b9c3a993de5ec015789

test:
  secret_key_base: 50e27d08ada11335708fc809ac493be2b79c973483f6637bbfcc7b2808e9507503ed24eda231128a0cfe5a272e40286cbc65e9bee6c0c5dfaefd8170f6d4b320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
